### PR TITLE
Clean up urls cache

### LINKED ISSUE #183: pytest.mark.urls does not properly clear the url cache
In the `restore` function in the `_django_set_urlconf`, `clear_url_caches()` must be called to actually clear the url after `ROOT_URLCONF` is restored

### PR DESCRIPTION
**Pull request by birdsarah**
This fixes #183, but I didn't write any tests for this change as just needed a quick fix and not immediately sure how to test.

### CODE REVIEW

**Comment by blueyed** [comment]
Thanks!
Please squash that into a single commit.

Also, a test should be added. It should be not too hard.
We could look into it when merging.

**Comment by pelme** [comment]
@birdsarah Thanks for the patch! Would you like to submit a test to this so that we can merge it? I plan on putting out a new release in a couple of days, it would be great to have this issue fixed!

**Comment by birdsarah** [comment]
@pelme. Thanks for the message. I don't know how to test, and am afraid I don't have time to get my head into it in the next couple of days as am at europython.

**Comment by pelme** [comment]
@birdsarah No problems! If you want to give it a go there is a pytest sprint going on tomorrow in the europython sprints. I was there today but am going home early tomorrow but there are a lot of people knowledgeable about pytest around if you need help :)

**Comment by birdsarah** [comment]
@pelme - we did it :D - big thanks to @davidszotten at Europython.

**Comment by pelme** [comment]
Thank you very much! Too bad I missed you at the sprints, but see you next year! :)

The tests fail on Django 1.3 (the import for `from django.conf.urls import patterns, url` should also try importing from `from django.conf.urls.defaults import patterns, url`): https://travis-ci.org/pytest-dev/pytest-django/jobs/72688782#L225

There is also a linter violation: https://travis-ci.org/pytest-dev/pytest-django/jobs/72688796#L136-L139

I can fix those when I merge this, but it might be nice to do the last bits too. Let me know either way and I will try to merge this soon!

**Comment by birdsarah** [comment]
Will push a fix today.

**Comment by blueyed** [comment]
:+1:

**Comment by k4nar** [comment]
Nice work, I was just about to submit a similar PR :) .

**Comment by k4nar** [comment]
Actually, I wonder if we shouldn't call `set_urlconf(None)` also when setting the temporary `ROOT_URLCONF`. This is what is done in `TestCase` here: https://github.com/django/django/blob/master/django/test/testcases.py#L239

**Comment by pelme** [comment]
Thanks everyone, I have merged this and added a call to `set_urlconf(None)` as suggested by @k4nar .

**Pull request closed without merging**
