### PR TITLE
Added a new option  to avoid forcing of DEBUG setting to False

### LINKED ISSUE #228: why DEBUG is hardcoded to False?
Hi

https://github.com/pytest-dev/pytest-django/blob/master/pytest_django/plugin.py#L239

this looks not too flexible
I tried a lot of things before i found this hardcode - i needed to understand why my liveserver fails, and it returned just standard 500 instead of debug page, and debug is set to True in my test settings
So i think this hardcode should be removed to respect test settings

### PR DESCRIPTION
**Pull request by bubenkoff**
closes #228

### CODE REVIEW

**Comment by bubenkoff** [comment]
@blueyed, @pelme 
can you please review?

**Comment by blueyed** [comment]
I find the option name confusing, because of the double negation.

Given that, I think it might be better to make the option control the `DEBUG` setting. Something like `--django-debug`, which would default to `False` (current behavior) and could be also `True` (enable debugging from pytest), or `None` (do not force setting/changing it).

**Comment by blueyed** [comment]
@bubenkoff 
What's your opinion on my comment / feedback?

**Comment by bubenkoff** [comment]
i agree, will change the PR

On 29/04/2015, Daniel Hahler <notifications@github.com> wrote:
> @bubenkoff
> What's your opinion on my comment / feedback?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/pytest-dev/pytest-django/pull/231#issuecomment-97376272


-- 
Anatoly Bubenkov

**Comment by osantana** [comment]
:+1:

**Comment by pelme** [comment]
@bubenkoff Sorry for the delay, it is now merged, will hopefully put out a new release later today :)

**Comment by blueyed** [comment]
@pelme 
That should not have been merged yet: https://github.com/pytest-dev/pytest-django/pull/231#issuecomment-93381011

**Comment by pelme** [comment]
Oops, sorry about that, I have reverted the merge in 3cd0d32c0f92908251eaa397ad61596c988aaa45.

**Comment by pelme** [comment]
Meh. github won't allow re-opening a pull request. @bubenkoff can you please create a new PR? Sorry for the mess. :(

**Comment by bubenkoff** [comment]
no problem

**Pull request merged**
