### PR TITLE
Add testcase to show erroneous multiple runs of django.setup()

### PR DESCRIPTION
**Pull request by pakal**
Testcase to advance on  https://github.com/pytest-dev/pytest-django/issues/531

### CODE REVIEW

**Comment by blueyed** [comment]
Rebased against master.
I think it could be fixed for Django 2.0 at least given https://code.djangoproject.com/ticket/27176 (https://github.com/django/django/pull/7682).

**Comment by blueyed** [comment]
Will include this into https://github.com/pytest-dev/pytest-django/pull/629.

**Comment by blueyed** [comment]
I think the test added to https://github.com/pytest-dev/pytest-django/pull/629/files#diff-b8f370066f4a8dcc417f6e09e1689a84 is enough to test this, do you agree?

**Comment by blueyed** [comment]
Backed out the changes in #629, basically only fixing this issue now.

**Comment by pakal** [comment]
Yes the test added above seems to make the same as mine, ensuring django.setup() is only called once

**Comment by pakal** [comment]
Thanks !

**Pull request closed without merging**
