### PR TITLE
Add support for serialized rollback

### LINKED ISSUE #329: Tests using live_server fixture removing data from data migrations
I've created a simple test case to reproduce this behavior https://github.com/ekiro/case_pytest/blob/master/app/tests.py which fails after second test using live_server fixture. 
MyModel objects are created in migration, using RunPython. It looks like after any test with live_server, every row from the database is truncated.

### PR DESCRIPTION
**Pull request by luzfcb**
Fixes #329.

TODO:

- [ ] add  test(s)

This is the code made by @blueyed in #353 with some additional inspired by #619

This issue reported by @aaugustin seems to be a blocker
https://code.djangoproject.com/ticket/26552

### CODE REVIEW

**Comment by luzfcb** [comment]
Is there any particular reason for the current Travis-ci configuration only testing against MySQL using Python2 + 7 + Django 1.11, and not testing against the new versions of django and python3?

**Comment by blueyed** [comment]
> Is there any particular reason for the current Travis-ci configuration only testing against MySQL using Python2.7 + Django 1.11, and not testing against the new versions of django and python3?

It is meant to have a smaller build matrix.

**Comment by lapp0** [comment]
Thanks for this, hoping to see this in master soon!

Your branch gives me this warning:
```
  /nix/store/ih3aih50m19mdhlr07f1lhandghj07qv-python3.7-pytest-django-3.5.1/lib/python3.7/site-packages/pytest_django/fixtures.py:223: PytestDeprecationWarning: The `funcargnames` attribute was an alias for `fixturenames`, since pytest 2.3 - use the newer attribute instead.
    if "django_db_serialized_rollback" in request.funcargnames:
```

**Comment by luzfcb** [comment]
@lapp0 Thanks for pointing me the warnings. I already fix the code.

Anyway, a key duplication error is occurring, however, this seems to be erratic behavior since the same commit causes the test suite to fail differently on two different instances of travis-ci

https://travis-ci.org/pytest-dev/pytest-django/builds/605222978

https://travis-ci.org/luzfcb/pytest-django/builds/605222952

**Comment by luzfcb** [comment]
The ticket https://code.djangoproject.com/ticket/26552 was solved in Django master branch.

https://github.com/django/django/pull/12736
https://github.com/django/django/pull/12651
https://github.com/django/django/pull/12453

**Comment by aleehedl** [comment]
@luzfcb Apart from resolving conflicts and adding tests, is there something else that needs to be done before this is ready for merging?

**Comment by coiax** [comment]
@aleehedl There are a number of work arounds in the comments of #329, although I haven't used any of them.

**Comment by daniel-ruiz** [comment]
@luzfcb Hi! I found this PR after encountering an error in a large Django test suite and it would be fantastic to count on this feature to solve that problem! 
Can I help in moving this forward? I'm not knowledgeable of pytest's internals, so I'd appreciate some pointers in order to get started 😄

**Comment by bluetech** [comment]
A PR which will replace this PR is in #970. I intend to merge and release it in a few days. Comments and tests are welcome.

**Pull request closed without merging**
