### PR TITLE
Fix deprecation warning

### PR DESCRIPTION
**Pull request by rpkilby**

### CODE REVIEW

**Comment by pelme** [comment]
Hmm, is there any chance we could have our own test suite catch any pytest warnings and fail? We should never ship a version that gives pytest-warnings.

I have not seen this warning myself in pytest-django itself or in my own project, where does it show up?

**Comment by rpkilby** [comment]
I found this while fixing deprecation warnings for DRF. Running their test suite w/ the `-Wonce` flag generates this warning as well as the one from #393.

**Comment by rpkilby** [comment]
> Hmm, is there any chance we could have our own test suite catch any pytest warnings and fail? We should never ship a version that gives pytest-warnings.

I was able to view errors w/ `python -Wonce -m pytest`. You could try to force errors w/ `-Werror`, but I was getting errors from other dependencies.

**Comment by blueyed** [comment]
See also https://github.com/fschulze/pytest-warnings.

**Comment by pelme** [comment]
Thanks for this PR! I've opened a new issue to track catching warnings in our CI setup: #415

**Pull request merged**
