### PR TITLE
Add changelog for 3.2 version

### PR DESCRIPTION
**Pull request by aniav**
As discussed in #473 it seems the only lacking point to release 3.1.3 version is the changelog. I have went through [all commits since last version](https://github.com/pytest-dev/pytest-django/compare/3.1.2...master) and written it down.

Let me know if I can improve it in any way, I'm happy to do so.

Additionally, thank you for working on `pytest-django`, it helps a ton with writing clean tests 🙏

### CODE REVIEW

**Comment by blueyed** [comment]
Thank you, slightly rephrased it.

@pelme 
Can you cut a release maybe this weekend, please?

**Comment by Smosker** [comment]
also waiting for these release

**Comment by aniav** [comment]
Friendly ping for updates 🙏

**Comment by blueyed** [comment]
Needs to be updated for recent changes (I guess since 794d6d5).
I am planning to do a release maybe this weekend or next week.

**Comment by blueyed** [comment]
Milestone: https://github.com/pytest-dev/pytest-django/milestone/5.

**Comment by aniav** [comment]
Does this mean you want me to make updates here, or are you going to do them yourself?

**Comment by blueyed** [comment]
Let's make updates here / based on this PR/branch.

**Comment by blueyed** [comment]
Amended in 6f41518.

**Pull request closed without merging**
