### PR TITLE
live_server: fix in-memory DB detection, dj 2.2 compat

### PR DESCRIPTION
**Pull request by blueyed**
Fixes https://github.com/pytest-dev/pytest-django/issues/783.

TODO:

- `dec_thread_sharing()` ?  (also for dj < 2.2 then likely)

### CODE REVIEW

**Comment by githubdd7** [comment]
Are there any plans to merge this change ? We think this can fix our pytest errors. Thank You.

**Comment by asfaltboy** [comment]
I'd love to pick it up, @blueyed could you provide some background on this PR, i.e with the changes that remove the thread logic, how will this still work?

**Comment by boxed** [comment]
I hit this exact problem today! Would love it if this was merged and released!

**Comment by bluetech** [comment]
Fixed in #973 (didn't see this one before...)

**Pull request closed without merging**
