### PR TITLE
Travis: test all Django versions against Python 2 and 3

### LINKED ISSUE #206: Travis: tests should include all Django versions on Python 2 and 3
It looks like the matrix generation from generate-configurations does not make sure that every Django version is tested on Python 2 and 3: https://travis-ci.org/pytest-dev/pytest-django/builds/50237861

It would be better to see that Django 1.5 also fails on Python 2.7.

### PR DESCRIPTION
**Pull request by blueyed**
Fixes #206.

### CODE REVIEW

**Comment by pelme** [comment]
Looks good to me, it doesn't really add that many more envs to Travis and it would be good to run them all. :-)

**Comment by blueyed** [comment]
Cool.  Rebased and will merge it when tests pass.

**Comment by pelme** [comment]
(The tests passed so I hit the merge button :-))

**Comment by blueyed** [comment]
Well done! :)

**Pull request merged**
