### PR TITLE
Use `travis_retry` in tox (via install_command), not on tox

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by pelme** [comment]
Very nice!

However, won't this affect local tox runs too? I run tox locally from time to time to run a specific configuration

**Comment by pelme** [comment]
Very nice with the wrapper!

**Comment by blueyed** [comment]
> However, won't this affect local tox runs too?

Yes..

The wrapper idea turned to be more complicated than initially hoped, but should work now.

**Comment by pelme** [comment]
I have a hard time doing any meaningful review by looking at the diff, but feel free to merge this if it works :)

**Pull request closed without merging**
