### PR TITLE
Generate _version.py file with setuptools_scm

### PR DESCRIPTION
**Pull request by fermezz**
Solves #757 by generating a `_version.py` file with `setuptools_scm`. I think using `post-release` as `version-scheme` is good because it lets you know the current version of the project, without doing anything more than splitting a string. Feedback is appreciated!

### CODE REVIEW

**Comment by blueyed** [comment]
I'd rather recommend using https://github.com/zsimic/setupmeta/.

**Comment by fermezz** [comment]
Ok nice! I was not aware of the `setupmeta` project. I have added a `__version__` attribute under `pytest_django/__init__.py` which matches what should be the version of this project if this is squashed and merged (3.5.1.post2). We can now have a workflow which would look like this for tagging a new version:

```(pytest-django) [fermezz@thinkpad pytest-django]$ python setup.py v→
  running version
  Not pushing bump, use --push to push
  Running: git add pytest_django/__init__.py
  Running: git commit -m "Version 3.5.2"
  [master 92eda6e] Version 3.5.2
   1 file changed, 1 insertion(+), 1 deletion(-)
  Running: git tag -a v3.5.2 -m "Version 3.5.2"
  (pytest-django) [fermezz@thinkpad pytest-django]$ cat pytest_django/__→
  __version__ = '3.5.2'```

_and_ we can get the version of the project as simple as `import pytest_django; pytest_django.__version__` which is great.

I didn't feel like it was necessary to put constraints to the version of `setupmeta` but if you think otherwise let me know!

**Comment by fermezz** [comment]
@blueyed ping for awareness! :)

**Comment by blueyed** [comment]
@fermezz 
Sorry for late reply, and thanks for this!

I'm not too sure about setupmeta anymore given that setuptools-scm is used already.

Also `pytest-django-3.7.1.dev3+g2bb0135` (master) looks better than `pytest-django-3.7.0.post4` (your cherry-picked PR), so it should use `versioning=devcommit` (resulting in `3.7.1.dev4-g64fd5d6-dirty`).

I'll leave this open for now (and can amend/change it to "devcommit" myself of course).

What do you think?

**Comment by fermezz** [comment]
Totally fine, @blueyed! I can take on that tomorrow, or the day after :)

**Comment by fermezz** [comment]
@blueyed Ok, so I went ahead and changed the versioning to `devcommit`. It's not as-straightforward to have that same versioning scheme with setuptools-scm and I don't see a big issue on changing it, but if you have a strong opinion on that, please let me know!

**Comment by blueyed** [comment]
@fermezz 
I've meant to keep using setuptools-scm more likely, but am still not sure.

What's your motiviation btw to have the version there?

**Comment by bluetech** [comment]
Done as part of #880.

**Pull request closed without merging**
