### PR TITLE
Add type=bool for django_find_project/INVALID_TEMPLATE_VARS_ENV

### PR DESCRIPTION
**Pull request by blueyed**
This refactors the _parse_django_find_project_ini method into
_get_boolean_value, and uses it for INVALID_TEMPLATE_VARS_ENV, too.

### CODE REVIEW

**Comment by pelme** [comment]
Hmm, did travis run?

**Comment by blueyed** [comment]
Now it does - pushed the same commit with a new hash.

**Comment by blueyed** [comment]
Not sure about since when `type='bool'` is supported by pytest though.

**Comment by blueyed** [comment]
`type='bool'` is supported since 2.9.0 only.

**Comment by blueyed** [comment]
We could require 2.9 or do something like https://github.com/s0undt3ch/pytest-instafail/blob/733c301eb848ff38c16613670f4797e88c081478/pytest_instafail.py#L24-L40.

**Comment by pelme** [comment]
Thanks! pytest >=2.9 is fine :)

**Pull request merged**
