### PR TITLE
document live_server and transactions problems. closes #229

### LINKED ISSUE #229: database table is locked: auth_user
When i try to log in to live_server with a browser, i get this:

```
OperationalError at /login/

database table is locked: auth_user

Request Method: 	POST
Request URL: 	http://localhost:8081/login/
```

do we keep transaction opened somewhere?

### PR DESCRIPTION
**Pull request by bubenkoff**

### CODE REVIEW

**Comment by blueyed** [comment]
The `live_server` fixture is meant to automatically take care of this.
Maybe this has regressed, or wasn't working properly?!

**Comment by bubenkoff** [comment]
it can't take care of this, actually
db fixture could, and it tries, just it's not easy: it checks if
live_server is used, but what if it's used, just LATER than db

On 10 April 2015 at 15:13, Daniel Hahler <notifications@github.com> wrote:

> The live_server fixture is meant to automatically take care of this.
> Maybe this has regressed, or wasn't working properly?!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pytest-dev/pytest-django/pull/230#issuecomment-91552351>
> .
>



-- 
Anatoly Bubenkov

**Comment by blueyed** [comment]
I've seen your comment at https://github.com/pytest-dev/pytest-django/issues/229#issuecomment-91469920 now.  Let's keep the discussion there.

**Comment by blueyed** [comment]
I am closing this, because I consider this to be a bug, and not a documentation issue.

**Pull request closed without merging**
