### PR TITLE
Set __package__ to fix import warnings

### LINKED ISSUE #495: ImportWarning with PYTHONWARNINGS=all
I like to use PYTHONWARNINGS=all for my test runs. Unfortunately, anything that uses pytest-django includes a ton of warnings from pytest_django/plugin.py:

```pytb
/home/adys/src/django/django-intenumfield/.tox/py36-django111/lib/python3.6/site-packages/_pytest/assertion/rewrite.py:7: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/home/adys/src/django/django-intenumfield/.tox/py36-django111/lib/python3.6/site-packages/pytest_django/plugin.py:17: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  from .django_compat import is_django_unittest  # noqa
/home/adys/src/django/django-intenumfield/.tox/py36-django111/lib/python3.6/site-packages/pytest_django/plugin.py:18: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  from .fixtures import django_db_setup  # noqa
/home/adys/src/django/django-intenumfield/.tox/py36-django111/lib/python3.6/site-packages/pytest_django/fixtures.py:9: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  from . import live_server_helper
/home/adys/src/django/django-intenumfield/.tox/py36-django111/lib/python3.6/site-packages/pytest_django/fixtures.py:11: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  from .django_compat import is_django_unittest
/home/adys/src/django/django-intenumfield/.tox/py36-django111/lib/python3.6/site-packages/pytest_django/fixtures.py:12: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  from .pytest_compat import getfixturevalue
/home/adys/src/django/django-intenumfield/.tox/py36-django111/lib/python3.6/site-packages/pytest_django/fixtures.py:14: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  from .lazy_django import get_django_version, skip_if_no_django
/home/adys/src/django/django-intenumfield/.tox/py36-django111/lib/python3.6/site-packages/pytest_django/plugin.py:19: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  from .fixtures import django_db_use_migrations  # noqa
/home/adys/src/django/django-intenumfield/.tox/py36-django111/lib/python3.6/site-packages/pytest_django/plugin.py:20: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  from .fixtures import django_db_keepdb  # noqa
/home/adys/src/django/django-intenumfield/.tox/py36-django111/lib/python3.6/site-packages/pytest_django/plugin.py:21: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  from .fixtures import django_db_modify_db_settings  # noqa
/home/adys/src/django/django-intenumfield/.tox/py36-django111/lib/python3.6/site-packages/pytest_django/plugin.py:22: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  from .fixtures import django_db_modify_db_settings_xdist_suffix  # noqa
/home/adys/src/django/django-intenumfield/.tox/py36-django111/lib/python3.6/site-packages/pytest_django/plugin.py:23: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  from .fixtures import _live_server_helper  # noqa
/home/adys/src/django/django-intenumfield/.tox/py36-django111/lib/python3.6/site-packages/pytest_django/plugin.py:24: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  from .fixtures import admin_client  # noqa
/home/adys/src/django/django-intenumfield/.tox/py36-django111/lib/python3.6/site-packages/pytest_django/plugin.py:25: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  from .fixtures import admin_user  # noqa
/home/adys/src/django/django-intenumfield/.tox/py36-django111/lib/python3.6/site-packages/pytest_django/plugin.py:26: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  from .fixtures import client  # noqa
/home/adys/src/django/django-intenumfield/.tox/py36-django111/lib/python3.6/site-packages/pytest_django/plugin.py:27: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  from .fixtures import db  # noqa
/home/adys/src/django/django-intenumfield/.tox/py36-django111/lib/python3.6/site-packages/pytest_django/plugin.py:28: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  from .fixtures import django_user_model  # noqa
/home/adys/src/django/django-intenumfield/.tox/py36-django111/lib/python3.6/site-packages/pytest_django/plugin.py:29: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  from .fixtures import django_username_field  # noqa
/home/adys/src/django/django-intenumfield/.tox/py36-django111/lib/python3.6/site-packages/pytest_django/plugin.py:30: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  from .fixtures import live_server  # noqa
/home/adys/src/django/django-intenumfield/.tox/py36-django111/lib/python3.6/site-packages/pytest_django/plugin.py:31: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  from .fixtures import rf  # noqa
/home/adys/src/django/django-intenumfield/.tox/py36-django111/lib/python3.6/site-packages/pytest_django/plugin.py:32: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  from .fixtures import settings  # noqa
/home/adys/src/django/django-intenumfield/.tox/py36-django111/lib/python3.6/site-packages/pytest_django/plugin.py:33: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  from .fixtures import transactional_db  # noqa
/home/adys/src/django/django-intenumfield/.tox/py36-django111/lib/python3.6/site-packages/pytest_django/plugin.py:34: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  from .pytest_compat import getfixturevalue
/home/adys/src/django/django-intenumfield/.tox/py36-django111/lib/python3.6/site-packages/pytest_django/plugin.py:36: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  from .lazy_django import (django_settings_is_configured,
```

Any idea why?

### PR DESCRIPTION
**Pull request by jleclanche**
Fixes #495 

Also see #415.

### CODE REVIEW

**Comment by blueyed** [comment]
What warning does it fix?
How is #395 related?

**Comment by jleclanche** [comment]
Sorry, typo, it fixes #495

**Comment by jleclanche** [comment]
Anyone?

**Comment by blueyed** [comment]
It is not clear to me why this is needed, can you elaborate?

Otherwise / in general it seems fine though.

**Comment by jleclanche** [comment]
@blueyed It fixes the deprecation warnings reported in #495. Running any pytest-django project with PYTHONWARNINGS=all has those in the logs which is quite annoying.

**Comment by blueyed** [comment]
@jleclanche 
I see, but it is not clear to me why there is this warning in the first place.
I see it when running pytest-django's tests itself, but only when not installing it / setting $PYTHONPATH like it is done in `tox.ini`.

**Comment by jleclanche** [comment]
I suspect it has to do with the way pytest loads plugins.

**Comment by blueyed** [comment]
Yes.

`PYTHONWARNINGS=all` triggers displaying them, but `pytest -W error` does neither display them, nor cause them to be errors.

Stacktrace:
```
% PYTHONWARNINGS=all p -W error tests/test_unittest.py
…/Vcs/pytest-django/.venv/lib/python3.6/site-packages/_pytest/assertion/rewrite.py:7: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
> …/Vcs/pytest-django/pytest_django/plugin.py(18)<module>()
-> from .django_compat import is_django_unittest  # noqa
(Pdb) bt
  …/Vcs/pytest-django/.venv/bin/pytest(11)<module>()
-> sys.exit(main())
  …/Vcs/pytest-django/.venv/lib/python3.6/site-packages/_pytest/config.py(50)main()
-> config = _prepareconfig(args, plugins)
  …/Vcs/pytest-django/.venv/lib/python3.6/site-packages/_pytest/config.py(160)_prepareconfig()
-> pluginmanager=pluginmanager, args=args)
  …/Vcs/pytest-django/.venv/lib/python3.6/site-packages/pluggy/__init__.py(617)__call__()
-> return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  …/Vcs/pytest-django/.venv/lib/python3.6/site-packages/pluggy/__init__.py(222)_hookexec()
-> return self._inner_hookexec(hook, methods, kwargs)
  …/Vcs/pytest-django/.venv/lib/python3.6/site-packages/pluggy/__init__.py(216)<lambda>()
-> firstresult=hook.spec_opts.get('firstresult'),
  …/Vcs/pytest-django/.venv/lib/python3.6/site-packages/pluggy/callers.py(180)_multicall()
-> res = hook_impl.function(*args)
  …/Vcs/pytest-django/.venv/lib/python3.6/site-packages/_pytest/config.py(943)pytest_cmdline_parse()
-> self.parse(args)
  …/Vcs/pytest-django/.venv/lib/python3.6/site-packages/_pytest/config.py(1108)parse()
-> self._preparse(args, addopts=addopts)
  …/Vcs/pytest-django/.venv/lib/python3.6/site-packages/_pytest/config.py(1071)_preparse()
-> self.pluginmanager.load_setuptools_entrypoints('pytest11')
  …/Vcs/pytest-django/.venv/lib/python3.6/site-packages/pluggy/__init__.py(397)load_setuptools_entrypoints()
-> plugin = ep.load()
  …/Vcs/pytest-django/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py(2408)load()
-> return self.resolve()
  …/Vcs/pytest-django/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py(2414)resolve()
-> module = __import__(self.module_name, fromlist=['__name__'], level=0)
  <frozen importlib._bootstrap>(961)_find_and_load()
  <frozen importlib._bootstrap>(950)_find_and_load_unlocked()
  <frozen importlib._bootstrap>(646)_load_unlocked()
  <frozen importlib._bootstrap>(616)_load_backward_compatible()
  …/Vcs/pytest-django/.venv/lib/python3.6/site-packages/_pytest/assertion/rewrite.py(212)load_module()
-> py.builtin.exec_(co, mod.__dict__)
> …/Vcs/pytest-django/pytest_django/plugin.py(18)<module>()
-> from .django_compat import is_django_unittest  # noqa
```

**Comment by blueyed** [comment]
Filed https://github.com/pytest-dev/pytest/issues/3061 with pytest.

**Comment by blueyed** [comment]
Can you confirm that it is only an issue / displayed when using `-s`?

**Comment by blueyed** [comment]
Looks like a pytest issue (see https://github.com/pytest-dev/pytest/issues/3061).

Warnings can be ignored (temporary solution): https://github.com/nicoddemus/pytest/commit/3dd24f8d218408f421aa9c88b7343bbb54e423f8.

**Comment by jleclanche** [comment]
@blueyed Hey, sorry to get back to this so late but is this PR getting merged? I understand it's not the best fix but I'd really like to get rid of the warnings =/

**Comment by blueyed** [comment]
@jleclanche 
I'd rather get this fixed properly, especially since the reason for this is still unclear to me.
You can use the workaround from https://github.com/nicoddemus/pytest/commit/3dd24f8d218408f421aa9c88b7343bbb54e423f8.

**Comment by blueyed** [comment]
pytest has it fixed by now: https://github.com/pytest-dev/pytest/commit/50a0d4fa95b3f6a25e650cd977307aebf5507d65 (not yet released I guess)

Closing this here for now.

Thanks for the PR and discussion of course still!

**Pull request closed without merging**
