### PR TITLE
install_requires: do not allow pytest 4.2.0

### PR DESCRIPTION
**Pull request by blueyed**
Ref: https://github.com/pytest-dev/pytest/issues/4704

### CODE REVIEW

**Comment by nicoddemus** [comment]
This probably should be mentioned in the CHANGELOG right?

**Comment by nicoddemus** [comment]
Hmm on second thought it would probably be nice to mention that there's an incompatibility that's being work out.

**Comment by blueyed** [comment]
@nicoddemus 
Yes, it might make sense to mention that it is a known issue, and not pinned just-because.

But it should also have been pinned to `<4.2` - I've done it a bit hastly due to having no time after all, but considered it to be rather critical.

**Comment by nicoddemus** [comment]
Sure thing, no worries, appreciate taking the time to do it even if you don't have it. 👍

**Pull request merged**
