### PR TITLE
Added test for setting DSM in pytest_configure

### PR DESCRIPTION
**Pull request by julen**
This adds a test for #146.

### CODE REVIEW

**Comment by julen** [comment]
Rebased on top of master, note that this test is meant to fail until #146 is fixed. @pelme can you have a look at this, please?

**Comment by pelme** [comment]
Thanks for the test, it will make the fix much easier. I have a very busy week and will try to look into this as soon as I can. I wanted to get 2.8.0 out quick to support Django 1.8 so this unfortunately had to wait for the moment.

**Comment by pelme** [comment]
(If you or anyone else want to work on this til I can look into it, please go ahead :))

**Comment by blueyed** [comment]
The fix for this might be simple: just remove the assertion, which is not correct in this case.

I've created a PR with the test and the fix at https://github.com/pytest-dev/pytest-django/pull/216.

**Comment by blueyed** [comment]
Closing this in favor of #216, which includes the test and fix.

**Comment by julen** [comment]
Fair enough, and thanks for the fix!

**Pull request closed without merging**
