### PR TITLE
re-introduced auto clearing of mail.outbox

### LINKED ISSUE #433: 3.1.0 not backward compatible with 3.0.0
Does this project use semver? It looks like there's a backward-incompatible change between 3.0.0 and 3.1.0 that ended up failing any tests that relied on `mail.outbox`. What versions should we be tracking to avoid backward-incompatible changes?

### PR DESCRIPTION
**Pull request by peterlauri**
Closes #433

### CODE REVIEW

**Comment by pelme** [comment]
Thank you!

Wouldn't replacing `mail.outbox` like this be a regression from the fix in #407?

**Comment by peterlauri** [comment]
@pelme so true, fixed that and squashed...

**Comment by pelme** [comment]
Sorry to not noticed the first time around, but is the monkeypatch in mailoutbox really necessary now? Wouldn't just `return mail.outbox` be enough?

**Comment by peterlauri** [comment]
@pelme so true again, fix and squash... But now there is no code to maintain anymore... :(

**Comment by pelme** [comment]
Excellent :D

**Pull request merged**
