### PR TITLE
in django >= 1.9 one can set module value to None in settings.MIGRATION_MODULES to not run

### LINKED ISSUE #417: Tests are failing for Django master
I'd like to make a release but we should fix this first.

Output from the failing test:
https://travis-ci.org/pytest-dev/pytest-django/jobs/173636497

### PR DESCRIPTION
**Pull request by peterlauri**
Closes #417

### CODE REVIEW

**Comment by blueyed** [comment]
Awesome!
Is this documented?

**Comment by peterlauri** [comment]
Do you mean documented in Django? If so, yes:

https://github.com/django/django/blob/master/django/db/migrations/questioner.py#L41

**Comment by pelme** [comment]
Thanks! This looks good to me. The migration skipping has always been a hack and this looks less so to me. :)

**Comment by peterlauri** [comment]
With exception to Django 1.8 and below that stays the same. Thanks for merging it!

**Pull request merged**
